### PR TITLE
Add two use cases to forks

### PR DESCRIPTION
**Pull request by GeorgLink**
Hi GMD workgroup,

I just had an interview and we discussed forks. 
I am sure there is literature to back up the two use cases, but I wanted to make sure to capture this thought first and we can improve on it later.

Best,
Georg

### CODE REVIEW

**Comment by sgoggins** [comment]
@GeorgLink : I think some conflicts were introduced during the last pull request approval. Can you see if those can be resolved with some minor edits and resubmit?

**Comment by sgoggins** [comment]
We have moved this work to the wg-gmd branch of the metrics repository.  Please resubmit this pull request there.

**Comment by GeorgLink** [comment]
Sure, I should be able to resolve merge conflicts within the same pull request.

**Comment by GeorgLink** [comment]
I see what happened. Because the files moved, resolving this was more difficult than it was worth. New pull request: #21

**Pull request closed without merging**
