### PR TITLE
Repository Structure and File Name Convention

### PR DESCRIPTION
**Pull request by klumb**
There is a lot here and I took some liberties on naming the metrics files so it may be helpful to discuss the 30 metrics we have identified so far (according to the goal documents) in the next meeting to make certain we have shared understanding of what they are and the names are accurate. 

(or comments/edits here)

For the most part, I left the metrics files untouched other than changing the name or creating a file if it was missing.

I moved the metrics that aren't linked in the goal pages to an archived metrics folder.

I created a focus area folder to hold the goals and use cases. I believe this is the structure that was discussed.

I also made minor changes to the repository structure and some of the organization documents. 

Resolves:
#24 
#7 
#4 

@sgoggins 
@jgbarah 
Please Review

### CODE REVIEW

**Comment by klumb** [comment]
I am not sure what .DS_Store was it showed up 5 or 6 months ago. I deleted it.

**Comment by klumb** [comment]
Sorry, slipped and hit wrong button

**Comment by jgbarah** [comment]
@klumb, anything about this?:

> Why are we using numbers for starting folder names? (I mean, such as 1_template_folder instead of template_folder

**Comment by klumb** [comment]
@jgbarah, also not needed.

**Pull request merged**
