### PR TITLE
[use_cases] Add directory and description for use cases.

### PR DESCRIPTION
**Pull request by jgbarah**
This is a preliminar version, to start working with use cases.

### CODE REVIEW

**Comment by sgoggins** [comment]
Isn't this what we would put into the "Focus Areas" Folders if we are following the D&I Structure?

**Comment by sgoggins** [comment]
Following up on my comment just now, Underneath "Focus Areas" I see the specific metrics defined. I know we have discussed using Use Cases, but I do not see them in the D&I Structure. @GeorgLink : Can you advise regarding how D&I is handling use case definitions and if any are committed to the repository yet? Or, if the use cases are embedded in your metrics definitions?

**Comment by jgbarah** [comment]
As far as I know, D&I are not using use cases in this way. The idea here came from several people in CHAOSS having interesting experiences on using (or willing to use) metrics, which could be useful for defining the questions and framing the metrics.

The idea of these use case is to be orthogonal to the "focus area | goal | question | metric" structure (therefore the different directory).

**Comment by GeorgLink** [comment]
In D&I, we do not use the term 'use case'. What we include on our resource pages are 'objectives', which are not full fledged use cases but provide rationale for why to use metrics. [Example][1]

How does the use case compare to our idea of the blog posts series [Metrics in Use][2] (which we still need to launch)?

[1]: https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus_areas/project_and_community/documentation.md
[2]: https://docs.google.com/document/d/1p9FZM6rixjiEsxXQ7Ij-mbGCJKm_OrOQ6nd3oIBRnto/edit

**Comment by jgbarah** [comment]
> How does the use case compare to our idea of the blog posts series Metrics in Use (which we still need to launch)?

I think most use cases could be the basis for a blog post.

**Comment by jgbarah** [comment]
> One suggestion: Point to our blog post series as a possibility for disseminating the use case. https://docs.google.com/document/d/1p9FZM6rixjiEsxXQ7Ij-mbGCJKm_OrOQ6nd3oIBRnto/edit#heading=h.i08ikslakwjv

Good idea. I'm going to do it.

**Pull request merged**
