### PR TITLE
add two use cases to forks

### PR DESCRIPTION
**Pull request by GeorgLink**
Hi GMD workgroup,

I just had an interview and we discussed forks.
I am sure there is literature to back up the two use cases, but I wanted to make sure to capture this thought first and we can improve on it later.

Best,
Georg

### CODE REVIEW

**Comment by sgoggins** [comment]
We are no longer using this repository. Can you issue the pull request against the "wg-gmd" branch of the metrics repo?

**Comment by GeorgLink** [comment]
Will do.

An issue template would be great, that informs someone trying to open an issue or pull request that this is not the place.

**Comment by jgbarah** [comment]
I'm reopening this pr, since I think we agreed to follow up work here.

**Comment by sgoggins** [comment]
looks good to me. Just fix the directory.

**Comment by jgbarah** [comment]
@GeorgLink maybe you can amend the commit to avoid the current conflict? I guess it is a matter of changing the file name to the new one for this metric.

**Comment by GeorgLink** [comment]
I guess so. I'll have a look next week.

**Comment by GeorgLink** [comment]
I updated the branch to include the latest master version... 

When I `git diff` compare locally, it shows correctly that I only made a minor change.... this pull request shows way more.

**Comment by sgoggins** [comment]
Looks like this is a simple change, but the commits look more significant because things moved.

**Pull request closed without merging**
