### PR TITLE
Found typo while going through the file.

### PR DESCRIPTION
**Pull request by Polaris000**
Signed-off-by: Aniruddha Karajgi <akarajgi0@gmail.com>

### CODE REVIEW

**Comment by vchrombie** [comment]
Good catch, but I have an opened a PR this morning which has that change. :)
https://github.com/chaoss/wg-gmd/pull/112/files#diff-a1da987b25a7d8953456d7e19057feeaL19

**Comment by jgbarah** [comment]
As @vchrombie said, already fixed in @112. Thanks anyway!

**Comment by Polaris000** [comment]
Sorry, didn't notice this was included in a previous pull request, sent only a few hours before mine!.

**Comment by jgbarah** [comment]
No problem. Thanks anyway!

**Pull request closed without merging**
